version: '3'

services:
  dgf:
    build: ./DGF
    command: gunicorn -c gunicorn_config.py DGF.wsgi
    volumes:
      - ./DGF:/DGF
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    depends_on: 
      - dgf
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    volumes:
      - ./DGF/static:/var/www/static
      - ./DGF/media:/var/www/media

volumes:
  db_data:
    external: true