version: '3'

services:
  dgf:
    build: ./DGF
    command: gunicorn -c gunicorn_config.py DGF.wsgi
    volumes:
      - ./DGF:/DGF
    ports:
      - "8000:8000"

volumes:
  db_data:
    external: true