version: '3'

services:
  dgf:
    build: ./DGF
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./DGF:/DGF
    ports:
      - "8000:8000"

volumes:
  db_data:
    external: true